[default]
# Training
BATCH_SIZE = 32
NUM_ENVS = 32

NUM_EPISODES = 500000000

# shape characteristics
CIRCLE_EXTENT = 0.5 # extent of the coordinates
CIRCLE_MARGIN = 0.25 # margin left on the left side

TRIANGLE_EXTENT = 0.5 # extent of the coordinates
TRIANGLE_MARGIN = 0.25 # margin left on the left side

RECTANGLE_EXTENT = 0.4 # extent of the coordinates
RECTANGLE_MARGIN = 0.3 # margin left on the left side

RECTANGLE_MIN_SIZE = 0.05
RECTANGLE_MAX_SIZE = 0.3

# Optimization
LEARNING_RATE = 1e-4
WEIGHT_DECAY_ADAM = 0

# Model
IMG_SIZE = 256
NUM_CIRCLES = 1
NUM_TRIANGLES = 1
NUM_RECTANGLES = 1
TRIANGLE_SCALE = 2
# Device
DEVICE = "mps"

# Temperature settings for action sampling
TEMP_START = 0.1
TEMP_DECAY = 0.99
TEMP_MIN = 0.01
TEMP_UPDATE_INTERVAL = 100